### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by hanfeicode** [snower/forsun#5]
➜  ~ forsund -h              
Traceback (most recent call last):
  File "/usr/bin/forsund", line 7, in <module>
    from forsun.scripts.forsund import main
  File "/usr/lib/python2.7/site-packages/forsun/__init__.py", line 7, in <module>
    from . import config
  File "/usr/lib/python2.7/site-packages/forsun/config.py", line 6, in <module>
    import configparser
  File "/usr/lib/python2.7/site-packages/configparser.py", line 12, in <module>
    from backports.configparser import (
ImportError: No module named configparser
➜  ~ forsund 
Traceback (most recent call last):
  File "/usr/bin/forsund", line 7, in <module>
    from forsun.scripts.forsund import main
  File "/usr/lib/python2.7/site-packages/forsun/__init__.py", line 7, in <module>
    from . import config
  File "/usr/lib/python2.7/site-packages/forsun/config.py", line 6, in <module>
    import configparser
  File "/usr/lib/python2.7/site-packages/configparser.py", line 12, in <module>
    from backports.configparser import (
ImportError: No module named configparser

**Comment by hanfeicode** [comment]
➜  ~ pip install configparser
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: configparser in /usr/lib/python2.7/site-packages (3.5.0)

**Comment by snower** [comment]
只支持python3
可以重新安装一下，tornado发了6.0版本之后似乎也不知道，添加了锁定tornado5.1版本

**Comment by snower** [comment]
没遇到过你这个问题诶，是不是什么包没安装好

```
# pip freeze
backports-abc==0.5
configparser==3.5.0
futures==3.2.0
greenlet==0.4.14
hiredis==0.2.0
msgpack==0.5.6
psutil==5.4.7
pytz==2018.5
singledispatch==3.4.0.3
six==1.11.0
thrift==0.11.0
tornadis==0.8.1
tornado==5.1
torthrift==0.2.4
tzlocal==1.5.1
```
顺便不好意思，原来版本tornado发了6.0版本之后似乎也不支持了，重新安装下吧，添加了锁定tornado5.1版本
